// <auto-generated />
using HobbiesAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HobbiesAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240423113339_3tables")]
    partial class _3tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HobbiesAPI.Models.Hobby", b =>
                {
                    b.Property<int>("HobbyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HobbyId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HobbyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HobbyId");

                    b.ToTable("Hobbies");
                });

            modelBuilder.Entity("HobbiesAPI.Models.HobbyEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FKHobbyId")
                        .HasColumnType("int");

                    b.Property<int>("FKPeopleId")
                        .HasColumnType("int");

                    b.Property<string>("Links")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FKHobbyId");

                    b.HasIndex("FKPeopleId");

                    b.ToTable("HobbyEnrollments");
                });

            modelBuilder.Entity("HobbiesAPI.Models.People", b =>
                {
                    b.Property<int>("PeopleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeopleId"));

                    b.Property<string>("PeopleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("PeopleId");

                    b.ToTable("Peoples");
                });

            modelBuilder.Entity("HobbiesAPI.Models.HobbyEnrollment", b =>
                {
                    b.HasOne("HobbiesAPI.Models.Hobby", "Hobby")
                        .WithMany("HobbyEnrollments")
                        .HasForeignKey("FKHobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HobbiesAPI.Models.People", "People")
                        .WithMany("HobbyEnrollments")
                        .HasForeignKey("FKPeopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hobby");

                    b.Navigation("People");
                });

            modelBuilder.Entity("HobbiesAPI.Models.Hobby", b =>
                {
                    b.Navigation("HobbyEnrollments");
                });

            modelBuilder.Entity("HobbiesAPI.Models.People", b =>
                {
                    b.Navigation("HobbyEnrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
